module.exports = {
  sections: [
    {
      name: 'Hawk - Style Guide (WIP)',
      content: './README.md',
    },
    {
      name: 'Core UI Components',
      components: () => ([
        '../packages/button/src/index.js',
        '../packages/label/src/index.js',
        '../packages/input/src/index.js',
        '../packages/password-strength/src/index.js',
        '../packages/checkbox/src/index.js',
        '../packages/radio/src/index.js',
        '../packages/toggle/src/index.js',
        '../packages/loader/src/index.js',
        '../packages/modal/src/index.js',
        '../packages/navigation-drawer/src/index.js',
        '../packages/tabbed/src/index.js',
        '../packages/card/src/index.js',
        '../packages/image/src/index.js',
        '../packages/pagination/src/index.js',
        '../packages/table/src/index.js',
        '../packages/toast/src/index.js',
        '../packages/tag/src/index.js',
        '../packages/pill/src/index.js',
        '../packages/suggestions/src/index.js',
        '../packages/dropdown/src/index.js',
        '../packages/select-dropdown/src/index.js',
        '../packages/tags-input/src/index.js',
        '../packages/tooltip/src/index.js',
        '../packages/date-picker/src/index.js',
        '../packages/time-picker/src/index.js',
      ]),
    },
  ],
  template: './template.html',
  webpackConfig: require('./webpack.styleguide.js'),
};
