import _ from 'lodash';
import { fontSize, fontFamily } from '../constants';

export const getTools = [
  {
    id: 1,
    name: 'bold',
    field_type: 'button',
    aria: 'bold',
    tagNames: 'b',
    style: {
      prop: 'font-weight',
      value: 'bold',
    },
    contentDefault: 'B',
    contentFA: 'fas fa-bold',
    appearance: 'link',
  },
  {
    id: 2,
    name: 'italic',
    field_type: 'button',
    aria: 'italic',
    tagNames: 'i',
    style: {
      prop: 'font-style',
      value: 'italic',
    },
    contentDefault: 'I',
    contentFA: 'fas fa-italic',
    appearance: 'link',
  },
  {
    id: 3,
    name: 'underline',
    field_type: 'button',
    aria: 'underline',
    tagNames: 'u',
    style: {
      prop: 'text-decoration',
      value: 'underline',
    },
    contentDefault: 'U',
    contentFA: 'fas fa-underline',
    appearance: 'link',
  },
  {
    id: 4,
    name: 'link',
    field_type: 'button',
    aria: 'link',
    tagNames: 'link',
    style: {
      prop: '',
      value: '',
    },
    contentDefault: 'Link',
    contentFA: 'fas fa-link',
    appearance: 'link',
  },
  {
    id: 5,
    name: 'unlink',
    field_type: 'button',
    aria: 'unlink',
    tagNames: 'unlink',
    style: {
      prop: '',
      value: '',
    },
    contentDefault: 'Unline',
    contentFA: 'fas fa-unlink',
    appearance: 'unlink',
  },
  {
    id: 6,
    name: 'strikethrough',
    field_type: 'button',
    aria: 'strike through',
    tagNames: 'strike',
    style: {
      prop: 'text-decoration',
      value: 'line-through',
    },
    contentDefault: '<s>A</s>',
    contentFA: 'fas fa-strikethrough',
    appearance: 'link',
  },
  {
    id: 7,
    name: 'image',
    field_type: 'button',
    aria: 'image',
    tagNames: 'img',
    style: {},
    contentDefault: 'image',
    contentFA: 'far fa-image',
    appearance: 'link',
  },
  {
    id: 8,
    name: 'insertorderedlist',
    field_type: 'button',
    aria: 'ordered list',
    tagNames: 'ol',
    style: {
      prop: '',
      value: '',
    },
    contentDefault: '1.',
    contentFA: 'fas fa-list-ol',
    appearance: 'link',
  },
  {
    id: 9,
    name: 'insertunorderedlist',
    field_type: 'button',
    aria: 'unordered list',
    tagNames: 'ul',
    style: {
      prop: '',
      value: '',
    },
    contentDefault: '&bull;',
    contentFA: 'fas fa-list-ul',
    appearance: 'link',
  },
  {
    id: 10,
    name: 'copy',
    field_type: 'button',
    aria: 'copy',
    tagNames: '',
    style: {
      prop: '',
      value: '',
    },
    contentDefault: 'C',
    contentFA: 'fas fa-copy',
    appearance: 'link',
  },
  {
    id: 11,
    name: 'pre',
    field_type: 'button',
    aria: 'preformatted text',
    tagNames: 'pre',
    style: {
      prop: '',
      value: '',
    },
    contentDefault: '0101',
    contentFA: 'fas fa-code',
    appearance: 'link',
  },
  {
    id: 12,
    name: 'header',
    field_type: 'select',
    aria: 'header',
    tagNames: '',
    style: {
      prop: '',
      value: '',
    },
    suggest: {
      name: 'title',
      value: 'value',
      options: _.map(_.range(1, 7), (item) => (
        { title: `Heading ${item}`, value: `${item}` }
      )),
      style: 'formatblock',
    },
    contentDefault: 'Header',
    contentFA: '',
    appearance: 'button',
  },
  {
    id: 13,
    name: 'fontFamily',
    field_type: 'select',
    aria: 'font family',
    tagNames: '',
    style: {
      prop: 'font-family',
      value: '',
    },
    suggest: {
      name: 'title',
      value: 'value',
      options: _.map(fontFamily, (item) => (
        { title: item, value: item }
      )),
      style: 'fontname',
    },
    contentDefault: 'Font',
    contentFA: '',
    appearance: 'button',
  },
  {
    id: 14,
    name: 'fontSize',
    field_type: 'select',
    aria: 'font size',
    tagNames: '',
    style: {
      prop: 'font-size',
      value: '',
    },
    suggest: {
      name: 'title',
      value: 'value',
      options: _.map(fontSize, (item, index) => (
        { title: item, value: index + 1 }
      )),
      style: 'fontsize',
    },
    contentDefault: 'Size',
    contentFA: '',
    appearance: 'button',
  },
  {
    id: 15,
    name: 'textColor',
    field_type: 'color-picker',
    aria: 'text color picker',
    tagNames: '',
    style: {
      prop: 'forecolor',
      value: '',
    },
    contentDefault: 'A',
    contentFA: 'fas fa-font',
    appearance: 'link',
  },
  {
    id: 16,
    name: 'backgroundColor',
    field_type: 'color-picker',
    aria: 'background color picker',
    tagNames: '',
    style: {
      prop: 'backcolor',
      value: '',
    },
    contentDefault: 'A',
    contentFA: 'fas fa-fill-drip',
    appearance: 'link',
  },
  {
    id: 17,
    name: 'mergeTags',
    field_type: 'select',
    aria: 'merge tags',
    tagNames: '',
    style: {
      prop: '',
      value: '',
    },
    contentDefault: 'Merge Tags',
    contentFA: '',
    appearance: 'button',
  },
  {
    id: 18,
    name: 'insertHorizontalRule',
    field_type: 'button',
    aria: 'divider',
    tagNames: 'hr',
    style: {
      prop: '',
      value: '',
    },
    contentDefault: 'Divider',
    contentFA: 'fas fa-divide',
    appearance: 'link',
  },
  {
    id: 19,
    name: 'justifyLeft',
    field_type: 'button',
    aria: 'left justify',
    tagNames: '',
    style: {
      prop: 'text-align',
      value: 'left',
    },
    contentDefault: 'L',
    contentFA: 'fas fa-align-left',
    appearance: 'link',
  },
  {
    id: 20,
    name: 'justifyCenter',
    field_type: 'button',
    aria: 'center justify',
    tagNames: '',
    style: {
      prop: 'text-align',
      value: 'center',
    },
    contentDefault: 'C',
    contentFA: 'fas fa-align-center',
    appearance: 'link',
  },
  {
    id: 21,
    name: 'justifyRight',
    field_type: 'button',
    aria: 'right justify',
    tagNames: '',
    style: {
      prop: 'text-align',
      value: 'right',
    },
    contentDefault: 'R',
    contentFA: 'fas fa-align-right',
    appearance: 'link',
  },
  {
    id: 22,
    name: 'undo',
    field_type: 'button',
    aria: 'undo',
    tagNames: '',
    style: {
      prop: '',
      value: '',
    },
    contentDefault: 'U',
    contentFA: 'fas fa-undo',
    appearance: 'link',
  },
  {
    id: 23,
    name: 'redo',
    field_type: 'button',
    aria: 'redo',
    tagNames: '',
    style: {
      prop: '',
      value: '',
    },
    contentDefault: 'R',
    contentFA: 'fas fa-redo',
    appearance: 'link',
  },
];
