import _ from 'lodash';

export const getTools = [
  {
    id: 1,
    field_type: 'button',
    title: 'fas fa-bold',
    is_icon: true,
    appearance: 'link',
  },
  {
    id: 2,
    field_type: 'button',
    title: 'fas fa-italic',
    is_icon: true,
    appearance: 'link',
  },
  {
    id: 3,
    field_type: 'button',
    title: 'fas fa-underline',
    is_icon: true,
    appearance: 'link',
  },
  {
    id: 4,
    field_type: 'button',
    title: 'fas fa-link',
    is_icon: true,
    appearance: 'link',
  },
  {
    id: 5,
    field_type: 'button',
    title: 'fas fa-unlink',
    is_icon: true,
    appearance: 'link',
  },
  {
    id: 6,
    field_type: 'button',
    title: 'fas fa-strikethrough',
    is_icon: true,
    appearance: 'link',
  },
  {
    id: 7,
    field_type: 'button',
    title: 'far fa-image',
    is_icon: true,
    appearance: 'link',
  },
  {
    id: 8,
    field_type: 'button',
    title: 'fas fa-list-ol',
    is_icon: true,
    appearance: 'link',
  },
  {
    id: 9,
    field_type: 'button',
    title: 'fas fa-list-ul',
    is_icon: true,
    appearance: 'link',
  },
  {
    id: 10,
    field_type: 'button',
    title: 'fas fa-copy',
    is_icon: true,
    appearance: 'link',
  },
  {
    id: 11,
    field_type: 'button',
    title: 'fas fa-code',
    is_icon: true,
    appearance: 'link',
  },
  {
    id: 12,
    field_type: 'select',
    title: 'Styles',
    is_icon: false,
    appearance: 'button',
    suggest: {
      name: 'title',
      value: 'value',
      options: [
        { title: 'Heading 6', value: 'h6' },
        { title: 'Heading 5', value: 'h5' },
        { title: 'Heading 4', value: 'h4' },
        { title: 'Heading 3', value: 'h3' },
        { title: 'Heading 2', value: 'h2' },
        { title: 'Heading 1', value: 'h1' },
      ],
    },
  },
  {
    id: 13,
    field_type: 'select',
    title: 'Font',
    is_icon: false,
    appearance: 'button',
  },
  {
    id: 14,
    field_type: 'select',
    title: 'Size',
    is_icon: false,
    appearance: 'button',
    suggest: {
      name: 'title',
      value: 'value',
      options: _.map(_.range(10, 64), (item) => (
        { title: item, value: item }
      )),
    },
  },
  {
    id: 15,
    field_type: 'color-picker',
    title: 'fas fa-font',
    is_icon: true,
    appearance: 'button',
  },
  {
    id: 16,
    field_type: 'color-picker',
    title: 'fas fa-font',
    is_icon: true,
    appearance: 'button',
  },
  {
    id: 17,
    field_type: 'select',
    title: 'Merge Tags',
    is_icon: false,
    appearance: 'button',
  },
  {
    id: 18,
    field_type: 'button',
    title: 'fas fa-divide',
    is_icon: true,
    appearance: 'link',
  },
  {
    id: 19,
    field_type: 'button',
    title: 'fas fa-align-left',
    is_icon: true,
    appearance: 'link',
  },
  {
    id: 20,
    field_type: 'button',
    title: 'fas fa-align-center',
    is_icon: true,
    appearance: 'link',
  },
  {
    id: 21,
    field_type: 'button',
    title: 'fas fa-align-right',
    is_icon: true,
    appearance: 'link',
  },
  {
    id: 22,
    field_type: 'button',
    title: 'fas fa-undo',
    is_icon: true,
    appearance: 'link',
  },
  {
    id: 23,
    field_type: 'button',
    title: 'fas fa-redo',
    is_icon: true,
    appearance: 'link',
  },
];
