import _ from 'lodash';

export const getTools = [
  {
    id: 1,
    field_type: 'button',
    title: 'fas fa-bold',
    name: 'bold',
    is_icon: true,
    appearance: 'link',
  },
  {
    id: 2,
    field_type: 'button',
    title: 'fas fa-italic',
    name: 'italic',
    is_icon: true,
    appearance: 'link',
  },
  {
    id: 3,
    field_type: 'button',
    title: 'fas fa-underline',
    name: 'underline',
    is_icon: true,
    appearance: 'link',
  },
  {
    id: 4,
    field_type: 'button',
    title: 'fas fa-link',
    name: 'link',
    is_icon: true,
    appearance: 'link',
  },
  {
    id: 5,
    field_type: 'button',
    title: 'fas fa-unlink',
    name: 'unlink',
    is_icon: true,
    appearance: 'link',
  },
  {
    id: 6,
    field_type: 'button',
    title: 'fas fa-strikethrough',
    name: 'strike',
    is_icon: true,
    appearance: 'link',
  },
  {
    id: 7,
    field_type: 'button',
    title: 'far fa-image',
    name: 'image',
    is_icon: true,
    appearance: 'link',
  },
  {
    id: 8,
    field_type: 'button',
    title: 'fas fa-list-ol',
    name: 'ol-list',
    is_icon: true,
    appearance: 'link',
  },
  {
    id: 9,
    field_type: 'button',
    title: 'fas fa-list-ul',
    name: 'ul-list',
    is_icon: true,
    appearance: 'link',
  },
  {
    id: 10,
    field_type: 'button',
    title: 'fas fa-copy',
    name: 'copy',
    is_icon: true,
    appearance: 'link',
  },
  {
    id: 11,
    field_type: 'button',
    title: 'fas fa-code',
    name: 'code',
    is_icon: true,
    appearance: 'link',
  },
  {
    id: 12,
    field_type: 'select',
    title: 'Styles',
    is_icon: false,
    appearance: 'button',
    style: 'heading',
    suggest: {
      name: 'title',
      value: 'value',
      options: _.map(_.range(1, 7), (item) => (
        { title: `Heading ${item}`, value: `${item}` }
      )),
    },
  },
  {
    id: 13,
    field_type: 'select',
    title: 'Font',
    is_icon: false,
    appearance: 'button',
    style: 'fontFamily',
    suggest: {
      name: 'title',
      value: 'value',
      options: [
        { title: 'Arial', value: 'Arial' },
        { title: 'Comic Sans MS', value: 'Comic Sans MS' },
        { title: 'Courier New', value: 'Courier New' },
        { title: 'Georgia', value: 'Georgia' },
        { title: 'Helvetica', value: 'Helvetica' },
        { title: 'Lucida', value: 'Lucida' },
        { title: 'Tahoma', value: 'Tahoma' },
        { title: 'Times New Roman', value: 'Times New Roman' },
        { title: 'Trebuchet MS', value: 'Trebuchet MS' },
        { title: 'Verdana', value: 'Verdana' },
        { title: 'Arvo', value: 'Arvo' },
        { title: 'Lato', value: 'Lato' },
        { title: 'Lora', value: 'Lora' },
        { title: 'Merriweather', value: 'Merriweather' },
        { title: 'Merriweather Sans', value: 'Merriweather Sans' },
        { title: 'Noticia Text', value: 'Noticia Text' },
        { title: 'Open Sans', value: 'Open Sans' },
        { title: 'Playfair Display', value: 'Playfair Display' },
        { title: 'Roboto', value: 'Roboto' },
        { title: 'Source Sans Pro', value: 'Source Sans Pro' },
      ],
    },
  },
  {
    id: 14,
    field_type: 'select',
    title: 'Size',
    is_icon: false,
    appearance: 'button',
    style: 'fontSize',
    suggest: {
      name: 'title',
      value: 'value',
      options: _.map(_.range(10, 65), (item) => (
        { title: item, value: item }
      )),
    },
  },
  {
    id: 15,
    field_type: 'color-picker',
    title: 'fas fa-font',
    name: 'color-picker',
    is_icon: true,
    appearance: 'button',
  },
  {
    id: 16,
    field_type: 'color-picker',
    title: 'fas fa-font',
    name: 'color-picker',
    is_icon: true,
    appearance: 'button',
  },
  {
    id: 17,
    field_type: 'select',
    title: 'Merge Tags',
    is_icon: false,
    appearance: 'button',
  },
  {
    id: 18,
    field_type: 'button',
    title: 'fas fa-divide',
    name: 'divider',
    is_icon: true,
    appearance: 'link',
  },
  {
    id: 19,
    field_type: 'button',
    title: 'fas fa-align-left',
    name: 'align-left',
    is_icon: true,
    appearance: 'link',
  },
  {
    id: 20,
    field_type: 'button',
    title: 'fas fa-align-center',
    name: 'align-center',
    is_icon: true,
    appearance: 'link',
  },
  {
    id: 21,
    field_type: 'button',
    title: 'fas fa-align-right',
    name: 'align-right',
    is_icon: true,
    appearance: 'link',
  },
  {
    id: 22,
    field_type: 'button',
    title: 'fas fa-undo',
    name: 'align-undo',
    is_icon: true,
    appearance: 'link',
  },
  {
    id: 23,
    field_type: 'button',
    title: 'fas fa-redo',
    name: 'align-redo',
    is_icon: true,
    appearance: 'link',
  },
];
