export const defaultTheme = {
  container: 'hawk-color-picker__container',
  topWrapper: 'hawk-color-picker__wrapper-top',
  bottomWrapper: 'hawk-color-picker__wrapper-bottom',
  gradientContainer: 'hawk-color-picker__container-gradient',
  controlsContainer: 'hawk-color-picker__container-controls',
  toggleGroup: 'hawk-color-picker__toggle-group',
  toggleContainer: 'hawk-color-picker__toggle-container',
  toggle: 'hawk-color-picker__toggle',
  inputModeContainer: 'hawk-color-picker__container-input-mode',
  tileBackground: 'hawk-color-picker__tile',
  active: 'is-active',
  slider: 'slider',
  colorModeSlider: 'colormode-slider',
  colorModeSliderR: 'colormode-slider-r',
  colorModeSliderG: 'colormode-slider-g',
  colorModeSliderB: 'colormode-slider-b',
  colorModeSliderH: 'hawk-color-picker__colormode-slider__h',
  gradient: 'hawk-color-picker__gradient',
  gradientHue: 'hawk-color-picker__gradient-hue',
  gradientSaturation: 'gradient-saturation',
  gradientLight: 'gradient-light',
  gradientRHigh: 'gradient-rgb gradient-r-high',
  gradientRLow: 'gradient-rgb gradient-r-low',
  gradientGHigh: 'gradient-rgb gradient-g-high',
  gradientGLow: 'gradient-rgb gradient-g-low',
  gradientBHigh: 'gradient-rgb gradient-b-high',
  gradientBLow: 'gradient-rgb gradient-b-low',
  xyControlContainer: 'hawk-color-picker__control-xy-container',
  xyControl: 'hawk-color-picker__control-xy',
  xyControlDark: 'xy-control-dark',
  numberInputContainer: 'hawk-color-picker__container-number-input',
  numberInputLabel: 'hawk-color-picker__number-input-label',
  numberInput: 'hawk-color-picker__number-input',
  modeInputContainer: 'hawk-color-picker__container-mode-input',
  swatchCompareContainer: 'hawk-color-picker__container-swatch-compare',
};
