export const layoutOptions = [
  {
    id: 1,
    layouts: '<div class="hawk-email-editor-layout-section"><div class="hawk-email-editor-layout-banner"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div></div><div class="hawk-email-editor-layout-section"><div class="hawk-email-editor-layout-banner"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div></div>',
  },
  {
    id: 2,
    layouts: '<div class="hawk-email-editor-layout-section"><div class="hawk-email-editor-layout-banner"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div></div><div class="hawk-email-editor-layout-section"><div class="hawk-email-editor-layout-row"><div class="hawk-email-editor-layout-column"><div class="hawk-email-editor-layout-banner"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div></div><div class="hawk-email-editor-layout-column"><div class="hawk-email-editor-layout-banner"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div></div></div></div>',
  },
  {
    id: 3,
    layouts: '<div class="hawk-email-editor-layout-section"><div class="hawk-email-editor-layout-banner"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div></div><div class="hawk-email-editor-layout-section"><div class="hawk-email-editor-layout-row"><div class="hawk-email-editor-layout-column"><div class="hawk-email-editor-layout-banner"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div></div><div class="hawk-email-editor-layout-column"><div class="hawk-email-editor-layout-banner"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div></div><div class="hawk-email-editor-layout-column"><div class="hawk-email-editor-layout-banner"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div></div></div></div>',
  },
  {
    id: 4,
    layouts: '<div class="hawk-email-editor-layout-section"><div class="hawk-email-editor-layout-row"><div class="hawk-email-editor-layout-column"><div class="hawk-email-editor-layout-banner"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div></div><div class="hawk-email-editor-layout-column"><div class="hawk-email-editor-layout-banner"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div></div></div></div><div class="hawk-email-editor-layout-section"><div class="hawk-email-editor-layout-banner"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div></div>',
  },
  {
    id: 5,
    layouts: '<div class="hawk-email-editor-layout-section"><div class="hawk-email-editor-layout-row"><div class="hawk-email-editor-layout-column"><div class="hawk-email-editor-layout-banner"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div></div><div class="hawk-email-editor-layout-column"><div class="hawk-email-editor-layout-banner"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div></div></div></div><div class="hawk-email-editor-layout-section"><div class="hawk-email-editor-layout-row"><div class="hawk-email-editor-layout-column"><div class="hawk-email-editor-layout-banner"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div></div><div class="hawk-email-editor-layout-column"><div class="hawk-email-editor-layout-banner"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div></div></div></div>',
  },
  {
    id: 6,
    layouts: '<div class="hawk-email-editor-layout-section"><div class="hawk-email-editor-layout-banner"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div></div><div class="hawk-email-editor-layout-section"><div class="hawk-email-editor-layout-row"><div class="hawk-email-editor-layout-column"><div class="hawk-email-editor-layout-banner"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div></div><div class="hawk-email-editor-layout-column"><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div></div></div></div>',
  },
  {
    id: 7,
    layouts: '<div class="hawk-email-editor-layout-section"><div class="hawk-email-editor-layout-banner"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div></div><div class="hawk-email-editor-layout-section"><div class="hawk-email-editor-layout-row"><div class="hawk-email-editor-layout-column"><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div></div><div class="hawk-email-editor-layout-column"><div class="hawk-email-editor-layout-banner"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div></div></div></div>',
  },
  {
    id: 8,
    layouts: '<div class="hawk-email-editor-layout-section"><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-divider"></div><div class="hawk-email-editor-layout-row"><div class="hawk-email-editor-layout-column"><div class="hawk-email-editor-layout-divider"></div></div><div class="hawk-email-editor-layout-column"></div></div></div>',
  },
];
